# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Hira CLI — local agent runtime and management tool"
  homepage "https://github.com/hira-vn/cli"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hira-vn/cli/releases/download/v0.0.2/hira_darwin_amd64.tar.gz"
      sha256 "dc9f6b3927d46dfe9adc80999224f4150893f53e2382515b0b90093cee772437"

      define_method(:install) do
        bin.install "hira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hira-vn/cli/releases/download/v0.0.2/hira_darwin_arm64.tar.gz"
      sha256 "9a0d70fb0d6c6a2c56c86c2210af8b21a2c7222c20e95e48b5e3d2642b147042"

      define_method(:install) do
        bin.install "hira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hira-vn/cli/releases/download/v0.0.2/hira_linux_amd64.tar.gz"
      sha256 "924638257fbd668ec0534d7cd7c4329deac6d1119e711f5e2c34e2ef427c1ab3"
      define_method(:install) do
        bin.install "hira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hira-vn/cli/releases/download/v0.0.2/hira_linux_arm64.tar.gz"
      sha256 "4771d1441c3bd5d7c5cf8e687068a5a5f64ef454e5595d51f4e657c0b9b80684"
      define_method(:install) do
        bin.install "hira"
      end
    end
  end

  test do
    system "#{bin}/hira", "--version"
  end
end
